version: '2'
services:
  unfurl:
    container_name: unfurl
    build:
      context: ./
      dockerfile: Dockerfile
    # Match the port defined in config.ini
    ports:
      - "3000:3000"
    volumes:
      - ./unfurl.ini:/unfurl/unfurl.ini:ro
    restart: unless-stopped
